from typing import Protocol

from data_discovery.domain.models.discovery_result import DiscoveryResult
from data_discovery.domain.models.discovery_run_state import DiscoveryRunState


class DiscoveryEventLogger(Protocol):
    def log_started(self, state: DiscoveryRunState) -> None: ...
    def log_empty_page(self, state: DiscoveryRunState) -> None: ...
    def log_part_flushed(self, state: DiscoveryRunState, part_uri: str) -> None: ...
    def log_page_processed(self, state: DiscoveryRunState, page_size: int, page_matches: int) -> None: ...
    def log_rate_limit_sleeping(self, state: DiscoveryRunState, sleep_seconds: int) -> None: ...
    def log_completed(self, result: DiscoveryResult) -> None: ...
    def log_failed(self, snapshot_id: str, error: str) -> None: ...
